print("Bienvenido al programa, calculadora de ganancias para su empresa.")
print("")
nombre1=input("ingrese su primer nombre:",)
nombre2=input("ingrese su segundo nombre:",)
apellido1=input("ingrese su primer apellido:",)
apellido2=input("ingrese su segundo apellido:",)
print("")
empresa=input("Nombre de la Empresa:")
print("")
print("")
print("Bienvenido al sistema", nombre1, nombre2, apellido1, apellido2)
print("")
print("")
print("Empresa:"+ empresa)
print("")
print("")

GananciaEnero=int(input("ingrese las ganancias de Enero:"))
GananciaFebrero=int(input("ingrese las ganancias de Febrero"))
GananciaMarzo=int(input("ingrese las ganancias de Marzo:"))
print("")
print("")

gananciastotales= GananciaEnero +GananciaFebrero +GananciaMarzo
print("Las ganancias fueron de $:",gananciastotales)
print("")
print("")

print("Gracias por utilizar nuestros servicios, lo esperamos pronto.")
